### PR TITLE
refactoring

### PR DESCRIPTION
**Pull request by MonaxGT**

### CODE REVIEW

**Comment by jabbson** [comment]
Thank you for your interest in this code :)

Couple of things that caught my eye.

1) if we are to break my long, comprehensive and complex code into smaller pieces, could we normalize the mac address separately too; or better yet could we do validateNormalize, which would both change the string to the lower case and validate the correctness of the format. On top of all of that we could also strip off the new line at the end before we return the mac.

2) not quite sure why the 'defer' was demoted all the way to the bottom of the function, can we return it back to after the error checking, else could you please explain why are we having it there at the end, as it makes next to no sense since we are not postponing anything at this point - the very next line is a return statement.

Thanks,
A

**Comment by MonaxGT** [comment]
Hi A!

I glad to see, that you find my push request useful)

I've made some changes in my push request and add new function to normalize string with mac address and cut "\n" symbols. Agree with your about defer position and changed position for with function to top. I changed text in error message and tried to make some example about format, but understood that is long text message because we use 3 format of regular verb in your program. 

In my county we have problem with working this website without proxy and i think will be useful to modify proxy setting in http.DefaultClient. Definitely we should start to make tests....Gopher likes tests.

Thanks, 
M

**Comment by jabbson** [comment]
Hey, I never say no to collaboration, bud!

Few more things if you don't mind looking into if when you have time.

- The function name is about giving an idea about what is about to happen, I think Run could be named GetVendorName, so if in the **future** another function is added, it could have its own name (GetMacType perhaps, to print out things like universal/local and uc/mc or type of well known mac address).

- Function naming could be conventionalized / unified, for example if there is a function normalize, the other one could be verify, instead of verification (unless you disagree with this approach).

- Normalizing a mac should probably come before the verification, since we are only verifying lower-cased text or alternatively we could modify the regexp to also check for A-F and ditch the normalize function completely.

- It would make sense to parse the json of the final response, to properly display an error if there is one, in case our regexp doesn't work in some cases (i agree, tests should probably be added).

Apart from that, I think this is starting to look great.

Thanks,
A

**Comment by MonaxGT** [comment]
Hi A! 

Look at last commit I change names and add test.

**Pull request merged**
